from app.utils.logging_utils import get_logger

# Application loggers - each will be a singleton instance
app_logger = get_logger(name="main")
worker_logger = get_logger(name="worker")
llm_logger = get_logger(name="llm")
audio_logger = get_logger(name="audio")
goals_logger = get_logger(name="goals")
auth_logger = get_logger(name="auth")
cloudinary_logger = get_logger(name="cloudinary")
mongo_logger = get_logger(name="mongodb")
chroma_logger = get_logger(name="chromadb")
redis_logger = get_logger(name="redis")
calendar_logger = get_logger(name="calendar")
chat_logger = get_logger(name="chat")
image_logger = get_logger(name="image")
notes_logger = get_logger(name="notes")
search_logger = get_logger(name="search")
profiler_logger = get_logger(name="profiler")
general_logger = get_logger(name="general")
nltk_logger = get_logger(name="nltk")
langchain_logger = get_logger(name="langchain")
request_logger = get_logger(name="requests")
notification_logger = get_logger(name="notification")
mail_webhook_logger = get_logger(name="mail_webhook")
common_logger = get_logger(name="common")
