import LoginModal from "@/components/Login/LoginModal";
import Providers from "@/redux/providers";
import type { Metadata } from "next";
import { Toaster } from "sonner";
import "./globals.css";
// import SuspenseLoader from "@/components/Misc/SuspenseLoader";
// import { Suspense } from "react";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Providers>
          <LoginModal />
          <Toaster closeButton richColors position="top-right" theme="dark" />
          {children}
          {/* <Suspense fallback={<SuspenseLoader fullHeight fullWidth />}> */}
          {/* </Suspense> */}
        </Providers>
      </body>
    </html>
  );
}
