import type { Metadata } from "next";
import "./globals.css";
import { Suspense, useState } from "react";
import { Toaster } from "sonner";
import SuspenseLoader from "@/components/Misc/SuspenseLoader";
import LoginModal from "@/components/Login/LoginModal";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const [loginModalOpen, setLoginModalOpen] = useState(false);

  return (
    <html lang="en">
      <body>
        <LoginModal open={loginModalOpen} setOpen={setLoginModalOpen} />
        <Toaster closeButton richColors position="top-right" theme="dark" />
        <Suspense fallback={<SuspenseLoader fullHeight fullWidth />}>
          {children}
        </Suspense>
      </body>
    </html>
  );
}
