#!/bin/sh
# Store originally staged files
STAGED_FILES=$(git diff --cached --name-only)

# Run tools only on staged files
if [ -n "$STAGED_FILES" ]; then
  echo "$STAGED_FILES" | grep -E '\.(ts|tsx|js|jsx|json|md|css|scss)$' | xargs -r pnpm prettier --write
  echo "$STAGED_FILES" | grep -E '\.(ts|tsx|js|jsx)$' | xargs -r pnpm eslint --fix
  pnpm generate-barrels
  
  # Re-stage the modified files
  echo "$STAGED_FILES" | xargs -r git add
  git add src/**/index.ts
fi